spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

      properties:
        spring.json.trusted.packages: "demo.notificationservice.dto"
        spring.json.value.default.type: "demo.notificationservice.dto.OrderEvent"
logging:
  level:
    org.springframework.kafka: DEBUG
server:
  port: 8082