spring:
  application:
    name: inventory-service
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

      properties:
        spring.json.trusted.packages: "demo.inventoryservice.dto"
        spring.json.value.default.type: "demo.inventoryservice.dto.OrderEvent"
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/inventory_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.kafka: DEBUG
server:
  port: 8081